# Config option for dropping schema
drop_schema_and_all_data = true
# Config option for adding schema to dgraph
add_schema_on_start = true
# dgraph host
dgraph_host = "localhost:9080"
# import notes from Evernote folder
import_notes_evernote = false
# import notes from Evernote folder
import_notes_icloud = false
