version: "3"
services:
  pod:
    image: "gitlab.memri.io:5050/memri/pod:${POD_VERSION}"
    ports:
      - "0.0.0.0:3030:3030"
    networks:
      - memri-net
    volumes:
      - ./data/db:/data/db
      - ./data/files:/data/files
      - ./data/certs:/data/certs
      - /var/run/docker.sock:/var/run/docker.sock
    entrypoint:
      - "/pod"
      - "--owners=ANY"
      # Note that on a real system, you should not use non-https on 0.0.0.0
      - "--insecure-non-tls=0.0.0.0"
      - "--plugins-callback-address=http://pod_pod_1:3030"
      - "--plugins-docker-network=pod_memri-net"

networks:
  memri-net:
