// Constants used in the project. These are "convention over configuration" for now.

pub const DATABASE_DIR: &str = "./data/db";

pub const MEDIA_DIR: &str = "./data/media";

pub const SCHEMA_JSON_FILE: &str = "../res/autogenerated_database_schema.json";
